### ISSUE TITLE
Array items with their own anyof/oneof rules may be discarded from the model altogether

### ISSUE THREAD

**Issue by saper** [koxudaxi/datamodel-code-generator#1375] opened 2023-06-20 23:37 UTC
**Describe the bug**

if `anyOf`, `oneOf` contain only `required` rules and are used in parallel to the `properties` stanza in the definition of the object element of an array, no model classes for the array items will be produced.

Might be somewhat related to https://github.com/koxudaxi/datamodel-code-generator/issues/1312 
**To Reproduce**

Example schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
          "type": "object",
          "properties": {
                "positive": { "type": "boolean" },
                "negative": { "type": "boolean" }
          },
          "anyOf": [
                { "required": ["positive"] },
                { "required": ["negative"] }
          ]
   }
}


```

Used commandline:
```
$ datamodel-codegen --input m09.json --output m09.py
```
produces

```py
# generated by datamodel-codegen:
#   filename:  m09.json
#   timestamp: 2023-06-20T15:45:44+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Model(BaseModel):
    __root__: List
```

**Expected behavior**

`ModelItem` should be defined. Working example:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
          "type": "object",
          "oneOf": [
                {
                        "properties": {
                                "positive": { "type": "boolean" }
                        },
                        "required": ["positive"]
                },
                {
                        "properties": {
                                "negative": { "type": "boolean" }
                        },
                        "required": ["negative"]
                }
          ]
   }
}
```

produces

```py
# generated by datamodel-codegen:
#   filename:  m13.json
#   timestamp: 2023-06-20T15:59:55+00:00

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel


class ModelItem(BaseModel):
    positive: bool


class ModelItem1(BaseModel):
    negative: bool


class Model(BaseModel):
    __root__: List[Union[ModelItem, ModelItem1]]
```

**Version:**

 - OS: Red Hat Enterprise Linux 9
 - Python version: Python 3.9.16
 - datamodel-code-generator version: datamodel-code-generator==0.20.0

 - OS: FreeBSD 14-CURRENT
 - Python version: Python 3.9.16
 - datamodel-code-generator version: datamodel-code-generator 0.20.0+ commit 20b05345735dfa4ff1ef54c573935fbfed48a028

**Comment by koxudaxi** [comment] 2023-12-04 14:55
@saper 
The issue is fixed in the latest version.
Thank you so much!!

**Closed by koxudaxi** 2023-12-04 14:55 UTC
Labels: bug
