### ISSUE TITLE
Default options when using discriminators produce invalid pydantic models

### ISSUE THREAD

**Issue by blakehawkins** [koxudaxi/datamodel-code-generator#1125] opened 2023-02-20 11:15 UTC
**Describe the bug**
* Pydantic models [must](https://docs.pydantic.dev/usage/types/#discriminated-unions-aka-tagged-unions) use `Literal` type fields if those fields are discriminators
* datamodel-code-generator supports discriminators and literals, but by default produces unit models rather than literals
* This produces errors like:

```
pydantic.errors.ConfigError: Field 'mode' of model 'ConcreteTypeA' needs to be a `Literal`
```

**To Reproduce**

Example schema:
```json
...
        "discriminator": {
          "propertyName": "mode",
          "mapping": {
            "a": "#/components/schemas/ConcreteTypeA",
            "b": "#/components/schemas/ConcreteTypeB"
          }
        }
...
```

Used not command line but programmatically:
```
    datamodel_code_generator.generate(
        openapi_filename,
        target_python_version=datamodel_code_generator.PythonVersion.PY_39,
        output=destination,
        disable_timestamp=True,
        reuse_model=True,
        use_subclass_enum=True,
    )
```

Works if you add:

```
        enum_field_as_literal=datamodel_code_generator.LiteralType.One,
```

But this is a bit insideous because with that option added you also get single-field enums generated like this one:

```
class MyEnum(BaseModel):
    __root__: Literal['CARROT'] = Field(
        ..., description='An enumeration.', title='MyEnum'
    )
```

which invalidates existing code using `MyEnum.CARROT`.

**Expected behavior**

datamodel-code-generator should enforce that output pydantic models fields are always Literal if they're used as discriminators.

**Version:**
 - OS: Linux
 - Python version: 3.9
 - datamodel-code-generator version: 0.17.1

**Comment by ck-on-github** [comment] 2023-04-16 14:26
I am also running into the same issue with yaml spec. This makes it impossible to use oneOf with a discriminator. Are there any plans on fixing this?

**Comment by plexaikm** [comment] 2023-06-05 11:40
Something weird is happening... adding discriminator meta to JSON Schema (yes yes, not officially supported and only functional in openapi) generates the following behaviour:
1 - generates discriminator meta in Field but no Annotated wrapper
`
__root__: Union[
        ClassA,
        ClassB,
        ClassC,
    ] = Field(
        ...,
        description='content of description',
        discriminator='type',
    )
`
2 - actually works with pydantic although documentation suggest other syntax:
`
__root__: Annotated[Union[
        ClassA,
        ClassB,
        ClassC,
    ], Field(discriminator='type', description='content of description')]
` 

perhaps not a big change to fix it

**Comment by koxudaxi** [comment] 2023-12-04 16:18
@blakehawkins @ck-on-github @plexaikm 
The problem is fixed in the latest version.
Thank you very much!!

**Closed by koxudaxi** 2023-12-04 16:18 UTC
Labels: bug
