### ISSUE TITLE
Parsing the Open Captable schema fails

### ISSUE THREAD

**Issue by regebro** [koxudaxi/datamodel-code-generator#909] opened 2022-11-07 23:19 UTC
**Describe the bug**

I'm trying to parse the Open Captable Format schema (https://github.com/Open-Cap-Table-Coalition/Open-Cap-Format-OCF), but I do not succeed, despite trying several different ways.

My first attempt was by checking out the schema and pointing to it

> $ datamodel-codegen --input schema --output test

or

> $ datamodel-codegen --input schema/files/OCFManifestFile.schema.json --output test

(Same results)

But in that case `datamodel-codegen` will find references that are HTTPS links, and try to download them. However, the URL's have redirects, and `datamodel-codegen` will then try to interpret the resulting HTML error page, which fails. 

```
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1175, in root_id_context
    root_id: Optional[str] = root_raw.get('$id')
AttributeError: 'str' object has no attribute 'get'
```

Adding `follow_redirects=True`to the `httpx.get()` command only delays the error, as at some point it tries to resolve a URL that doesn't exist, and we get another error.

```
 Traceback (most recent call last):
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 574, in main
    generate(
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 371, in generate
    results = parser.parse()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 460, in parse
    self.parse_raw()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1242, in parse_raw
    self._parse_file(self.raw_obj, obj_name, path_parts)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1318, in _parse_file
    self.parse_obj(obj_name, root_obj, path_parts or ['#'])
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1207, in parse_obj
    self.parse_ref(obj, path)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1142, in parse_ref
    self.parse_ref(item, path)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1127, in parse_ref
    self.resolve_ref(obj.ref)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1117, in resolve_ref
    self._get_ref_body(relative_path),
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1068, in _get_ref_body
    return self._get_ref_body_from_url(resolved_ref)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1073, in _get_ref_body_from_url
    return self.remote_object_cache.get_or_put(
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/__init__.py", line 26, in get_or_put
    value = self[key] = default_factory(key)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1074, in <lambda>
    ref, default_factory=lambda key: load_yaml(self._get_text_from_url(key))
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 85, in load_yaml
    return yaml.load(stream, Loader=SafeLoader)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "yaml/_yaml.pyx", line 673, in yaml._yaml.CParser.get_single_node
  File "yaml/_yaml.pyx", line 687, in yaml._yaml.CParser._compose_document
  File "yaml/_yaml.pyx", line 731, in yaml._yaml.CParser._compose_node
  File "yaml/_yaml.pyx", line 847, in yaml._yaml.CParser._compose_mapping_node
  File "yaml/_yaml.pyx", line 860, in yaml._yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 2, column 1
could not find expected ':'
  in "<unicode string>", line 4, column 25
```

The references are `$id`s, so parsing through all the files in the directory first might fix this. 

I then try to replace the URL's with relative references using `#/schema/...` style ids.  This however leads to the following error:

```
Traceback (most recent call last):
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/__main__.py", line 574, in main
    generate(
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/__init__.py", line 371, in generate
    results = parser.parse()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/base.py", line 460, in parse
    self.parse_raw()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1244, in parse_raw
    self._resolve_unparsed_json_pointer()
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1264, in _resolve_unparsed_json_pointer
    self.parse_json_pointer(self.raw_obj, reserved_ref, path_parts)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 1277, in parse_json_pointer
    models = get_model_by_path(raw, object_paths)
  File "/home/lregebro/Shoobx/pyocf/ve/lib/python3.10/site-packages/datamodel_code_generator/parser/jsonschema.py", line 55, in get_model_by_path
    return get_model_by_path(schema[keys[0]], keys[1:])
KeyError: 'enums'
```

This is because it interprets a `#/enums/ValuationType.schema.json`  reference in the `objects/Valuation.schema.json` file as being relative to the Valuation schema, and looks for an `enum` key in that schema, instead of going back to the root of the schema and looking for it there. It's unclear to me from the JSON schema specification if this is the intended behavior, but if it is, how would you refer to something that is not a sub object in the schema?

How is this supposed to work?

Used commandline:
```
$ datamodel-codegen --input schema --output test --input-file-type jsonschema

Where the "schema" directory is the "schema" folder of a local checkout of the above repo.

**Expected behavior**
A generated schema.

**Version:**
 - OS: Linux
 - Python version: 3.10.6
 - datamodel-code-generator version: 0.13.5

**Additional context**

**Comment by regebro** [comment] 2022-11-12 12:08
Looking more on this, I *think* that it probably should not look up https references unless it's not anywhere in the tree of schemas, so it probably should parse all the schema files with unresolved references first, and then try to resolve them, and only look up https links if those ID's don't exist anywhere in the local files.

**Comment by regebro** [comment] 2022-11-28 16:54
We have decided that datamodel-codegen doesn't generate what we want, so we are rolling our own generator that are customized for the OCF schema, so feel free to close this as wontfix if you feel like it.

**Comment by koxudaxi** [comment] 2022-12-22 17:36
@regebro 
I'm sorry for my too-late reply.
I think this is a bug. I will fix it. 
Thank you very much.

**Comment by koxudaxi** [comment] 2023-12-04 15:44
@regebro 
The problem is fixed in the latest version.
You can generate the models with the schema.

**Closed by koxudaxi** 2023-12-04 15:44 UTC
Labels: bug
