### ISSUE TITLE
Generated code not working with discriminator literals

### ISSUE THREAD

**Issue by noncuro** [koxudaxi/datamodel-code-generator#1474] opened 2023-08-04 19:44 UTC
**Describe the bug**
Generated code doesn't work for `str` discriminators. The generated discriminator strings are `str` instead of `Literal`

**To Reproduce**

I'm using:
```
pydantic==2.1.1
pydantic_core==2.4.0
datamodel-code-generator==0.21.3
```

This is my (simplified) code:
```python
import json
from pathlib import Path
from typing import Literal, Union

import datamodel_code_generator
from pydantic import BaseModel, Field


class Type1(BaseModel):
    type_: Literal['a'] = 'a'

class Type2(BaseModel):
    type_: Literal['b'] = 'b'

class Response(BaseModel):
    inner: Union[Type1, Type2] = Field(..., discriminator='type_')


with open('schema.json', 'w') as f:
    json.dump(Response.model_json_schema(), f, indent=2)


datamodel_code_generator.generate(
    input_= Path('schema.json'),
    output_model_type=datamodel_code_generator.DataModelType.PydanticV2BaseModel,
)
```

**Generated Code:**

```python
from __future__ import annotations

from typing import Union

from pydantic import BaseModel, Field


class Type1(BaseModel):
    type_: str = Field('a', title='Type ')


class Type2(BaseModel):
    type_: str = Field('b', title='Type ')


class Response(BaseModel):
    inner: Union[Type1, Type2] = Field(..., discriminator='type_', title='Inner')
```

**Stacktrace when I run this**

```
PydanticUserError                         Traceback (most recent call last)
     14 
     15 
---> 16 class Response(BaseModel):
     17     inner: Union[Type1, Type2] = Field(..., discriminator='type_', title='Inner')

29 frames
[/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_discriminated_union.py](https://localhost:8080/#) in _infer_discriminator_values_for_inner_schema(self, schema, source)
    444 
    445         else:
--> 446             raise PydanticUserError(
    447                 f'{source} needs field {self.discriminator!r} to be of type `Literal`',
    448                 code='discriminator-needs-literal',

PydanticUserError: Model 'Type1' needs field 'type_' to be of type `Literal`
```

**Expected behavior**

**Version:**
 - OS: Google Colab
 - Python version: Python 3.10.12
 - datamodel-code-generator version: 0.21.3

**The schema**

```json
{
  "$defs": {
    "Type1": {
      "properties": {
        "type_": {
          "const": "a",
          "default": "a",
          "title": "Type "
        }
      },
      "title": "Type1",
      "type": "object"
    },
    "Type2": {
      "properties": {
        "type_": {
          "const": "b",
          "default": "b",
          "title": "Type "
        }
      },
      "title": "Type2",
      "type": "object"
    }
  },
  "properties": {
    "inner": {
      "discriminator": {
        "mapping": {
          "a": "#/$defs/Type1",
          "b": "#/$defs/Type2"
        },
        "propertyName": "type_"
      },
      "oneOf": [
        {
          "$ref": "#/$defs/Type1"
        },
        {
          "$ref": "#/$defs/Type2"
        }
      ],
      "title": "Inner"
    }
  },
  "required": [
    "inner"
  ],
  "title": "Response",
  "type": "object"
}
```

**Comment by ck-on-github** [comment] 2023-08-10 17:29
I was running into the same issue with discriminator in a yaml spec. 
I re-tried after this fix on Version: 0.21.4. But I am still seeing the same issue:

```
ParentModel:
      ...
      sampleInput:
        oneOf:
          - $ref: '#/definitions/SampleInput1'
          - $ref: '#/definitions/SampleInput2'
          - $ref: '#/definitions/SampleInput3'
        discriminator:
          propertyName: inputType
          mapping:
            input1: '#/definitions/SampleInput1'
            input2: '#/definitions/SampleInput2'
            input3: '#/definitions/SampleInput3'
```

```
  SampleInput1:
    type: object
    required:
      - inputType
    properties:
      inputType:
          type: string
```

SampleInput2 and SampleInput3 models also have the same required `inputType` attribute.

I generate the code with:
`datamodel-codegen --input api.yaml --input-file-type jsonschema  --output ../hcs/api_models/generated_models.py --target-python-version 3.8 --validation --use-title-as-name --disable-timestamp --strict-types {str,bytes,int,float,bool} --use-subclass-enum`

The generated code looks like this:

```
class SampleInput1(BaseModel):
    class Config:
        extra = Extra.forbid

    inputType: StrictStr

class ParentModel(BaseModel):
    sampleInput: Optional[
        Union[
            SampleInput1, SampleInput2, SampleInput3
        ]
    ] = Field(None, discriminator='inputType')

```

When I try to use the model, I see:


```
pydantic/main.py:204: in pydantic.main.ModelMetaclass.__new__
    ???
pydantic/fields.py:488: in pydantic.fields.ModelField.infer
    ???
pydantic/fields.py:419: in pydantic.fields.ModelField.__init__
    ???
pydantic/fields.py:534: in pydantic.fields.ModelField.prepare
    ???
pydantic/fields.py:636: in pydantic.fields.ModelField._type_analysis
    ???
pydantic/fields.py:750: in pydantic.fields.ModelField.prepare_discriminated_union_sub_fields
    ???
pydantic/utils.py:740: in pydantic.utils.get_discriminator_alias_and_values
    ???
E   pydantic.errors.ConfigError: Field 'sampleInput' of model 'SampleInput1' needs to be a `Literal`
```

Is there a way to get the `discriminator` attribute work with the yaml spec?

**Comment by koxudaxi** [comment] 2023-08-10 17:35
@ck-on-github 
plesae use `const` to define the value of `discriminator`

```yaml
SampleInput1:
  type: object
    required:
      - inputType
  properties:
    inputType:
      const: SampleInput1
      type: string
```

**Comment by ck-on-github** [comment] 2023-08-10 17:46
thanks for the prompt response.

with `const`, the generate code looks like:

```
class ErrorOnAnonymousHandling(BaseModel):
    inputType: StrictStr = Field('SampleInput1', const=True)
```

and still the same run time error...

**Comment by ck-on-github** [comment] 2023-08-10 17:50
Also, for what it is worth, per OpenAPI spec, I do not see any use of `const` with `discriminator`.

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by koxudaxi** [comment] 2023-08-10 18:01
I expect only pydantic v2 with const :thinking: 
`--output-model-type pydantic_v2.BaseModel`

https://docs.pydantic.dev/1.10/usage/types/#discriminated-unions-aka-tagged-unions

OK, we should convert the attribute type to literals for the OpenAPI.

```python
class SampleInput1(BaseModel):
    class Config:
        extra = Extra.forbid

    inputType: Literal['SampleInput1']

class ParentModel(BaseModel):
    sampleInput: Optional[
        Union[
            SampleInput1, SampleInput2, SampleInput3
        ]
    ] = Field(None, discriminator='inputType')

```

**Comment by koxudaxi** [comment] 2023-12-04 16:05
@noncuro @ck-on-github 
The problem is fixed in the latest version.
Thank you very much!!

**Closed by koxudaxi** 2023-12-04 16:05 UTC
Labels: bug
